research_task:
  description: |
    Conduct thorough research on the given topic using the DuckDuckGo search tool. 
    Your task is to:
    1. Use the search tool to find relevant and up-to-date information.
    2. Analyze and synthesize the search results to extract key insights.
    3. Organize the information in a clear and structured manner.
    4. Provide a comprehensive summary of your findings, including any conflicting information or differing viewpoints you may encounter.
    5. Cite your sources by including the search queries you used and a brief description of the most relevant results.
  agent: researcher
  expected_output: A detailed research report on the given topic, including key findings, analysis, and cited sources from DuckDuckGo searches.

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
